ln -s /skydive/Datasets/Makeup_Paired_Reconstruction_Iteration/train_inst_1 /skydive/Datasets/Makeup_Paired_Reconstruction_Iteration/train_inst
ln -s /skydive/Datasets/Makeup_Paired_Reconstruction_Iteration/test_inst_1 /skydive/Datasets/Makeup_Paired_Reconstruction_Iteration/test_inst
